[package]
name = "archive-witness-db-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
encoding_rs = "0.8.33"
image = "0.24.7"
lazy_static = "~1.4"
maplit = "1.0.2"
thiserror = "1.0.23"
uuid = "1.6.1"
